GET http://localhost:8080/retipy/patient/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJyZXRpcHkiLCJzdWIiOiJhbGV2YWx2IiwiaWRlbnRpdHkiOiIxMTExMTExMSIsInNjb3BlIjoidXNlcnMiLCJpYXQiOjE1MzQ2MzQ3MTAsImV4cCI6MTUzNDgwNzUxMH0.oM8FRTz3uVqRFJ5v0xDN9fWNPAy5Zd9CsIzs2QGeExA
