GET http://localhost:8080/retipy/patient/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJyZXRpcHkiLCJzdWIiOiJhbGV2YWx2IiwiaWRlbnRpdHkiOiIxMTExMTExMSIsInNjb3BlIjoidXNlcnMiLCJpYXQiOjE1MzUzMjY1NzAsImV4cCI6MTUzNTQ5OTM3MH0.ZcguljevwF-8Aai1HN_MkwIhgofVx4dTFhGA4nVsQio
