GET http://localhost:8080/retipy/patient/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJyZXRpcHkiLCJzdWIiOiJhbGV2YWx2IiwiaWRlbnRpdHkiOiIxMTExMTExMSIsInNjb3BlIjoidXNlcnMiLCJpYXQiOjE1MzM3Nzg1OTQsImV4cCI6MTUzMzc4MjE5NH0.PuCIKmx-lQtON7aW9Q4IV3l5NHs-zg7aqBdYjPvsbjc
