GET http://localhost:8080/retipy/diagnostic/2
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJyZXRpcHkiLCJzdWIiOiJhbGV2YWx2IiwiaWRlbnRpdHkiOiIxMjM0NTYiLCJzY29wZSI6InVzZXJzIiwiaWF0IjoxNTMyOTAxODg3LCJleHAiOjE1MzI5MDU0ODd9.RuVyMEGqtnUg237IxBsvFQ2bwhkXvdtXtrNxtkyS4B8
