POST http://localhost:8080/retipy/diagnostic
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJyZXRpcHkiLCJzdWIiOiJuZXdfdXNlciIsImlkZW50aXR5IjoiMTIzNDU2Iiwic2NvcGUiOiJ1c2VycyIsImlhdCI6MTUzMjkxNjIyMiwiZXhwIjoxNTMyOTE5ODIyfQ.aVhKeG_hpuGfizb1qe0qhTVvvHwoukKpYwSqKwOKPEA

{
  "id": "0",
  "diagnostic": "",
  "roiElementList": [
    {
      "notes": "Test",
      "roi_x": [
        134,
        97,
        172,
        313,
        197
      ],
      "roi_y": [
        351,
        425,
        515,
        461,
        383
      ]
    }
  ],
  "status": "UPDATED"
}
