POST http://localhost:8080/retipy/patient/1/opticalevaluation/2/diagnostic
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJyZXRpcHkiLCJzdWIiOiJhbGV2YWx2IiwiaWRlbnRpdHkiOiIxMTExMTExMSIsInNjb3BlIjoidXNlcnMiLCJpYXQiOjE1MzUzMzEwMzUsImV4cCI6MTUzNTUwMzgzNX0.od38AEZ0zS3Y0vsZ100L9ddw0HyBLCqC2bgxKnSydPo

{
  "id": "0",
  "diagnostic": "",
  "rois": [
    {
      "notes": "Test",
      "roi_x": [
        134,
        97,
        172,
        313,
        197
      ],
      "roi_y": [
        351,
        425,
        515,
        461,
        383
      ]
    }
  ],
  "status": "UPDATED"
}
