POST http://localhost:8080/retipy/user/enable
content-type: text/plain
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJyZXRpcHkiLCJzdWIiOiJhbGV2YWx2IiwiaWRlbnRpdHkiOiIxMTExMTExMSIsInNjb3BlIjoidXNlcnMiLCJpYXQiOjE1MzI5MTYxODgsImV4cCI6MTUzMjkxOTc4OH0.fIwURpeaTsvDs3CYCHW4Hfo4QxgNul0T2ZMXNWzXEI0

new_user
