POST {{host}}/retipy/user/token
content-type: text/plain

eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJyZXRpcHkiLCJzdWIiOiJhbGV2YWx2IiwiaWRlbnRpdHkiOiIxMjM0NTYiLCJzY29wZSI6InVzZXJzIiwiaWF0IjoxNTMyODk4NjgyLCJleHAiOjE1MzI4OTg2ODJ9.X_eNZNOVK_dYj0eFeaamLvC5dIPfYRzkgknRElzgsro
